DATA_DIR=../../../../nfs/nas-7.1/pwgao/data/PDTB-3.0/data
BASED_DIR=../../../../nfs/nas-7.1/pwgao/data/xlnet_cased_L-12_H-768_A-12
PRED_DIR=pred_dir
INIT_CKPT=${BASED_DIR}/xlnet_model.ckpt
EVAL_CKPT=exp/pdtb/model.ckpt-400
CUDA_VISIBLE_DEVICES=0 python3.6 run_classifier.py \
  --do_eval=True \
  --do_predict=True \
  --eval_all_ckpt=True \
  --task_name=pdtb \
  --data_dir=${DATA_DIR} \
  --output_dir=proc_data/pdtb \
  --model_dir=exp/pdtb \
  --uncased=False \
  --spiece_model_file=${BASED_DIR}/spiece.model \
  --model_config_path=${BASED_DIR}/xlnet_config.json \
  --init_checkpoint=${BASED_DIR}/xlnet_model.ckpt \
  --max_seq_length=128 \
  --eval_batch_size=32 \
  --predict_batch_size=32 \
  --predict_dir=${PRED_DIR} \
  --num_hosts=1 \
  --num_core_per_host=1