PDTB_DATA_DIR=../../../../nfs/nas-7.1/pwgao/data/PDTB-3.0/data
FIN_DATA_DIR=task1/
BASED_DIR=../../../../nfs/nas-7.1/pwgao/data/xlnet_cased_L-12_H-768_A-12
CUDA_VISIBLE_DEVICES=0 python3.6 run_classifier.py \
  --do_train=True \
  --do_eval=True \
  --eval_all_ckpt=True \
  --task_name=fincausal \
  --data_dir=${FIN_DATA_DIR} \
  --output_dir=proc_data/fincausal \
  --model_dir=exp/fincausal \
  --uncased=False \
  --spiece_model_file=${BASED_DIR}/spiece.model \
  --model_config_path=${BASED_DIR}/xlnet_config.json \
  --init_checkpoint=${BASED_DIR}/xlnet_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --eval_batch_size=8 \
  --num_hosts=1 \
  --num_core_per_host=1 \
  --learning_rate=1e-5 \
  --adam_epsilon=1e-8 \
  --train_steps=4000 \
  --warmup_steps=200 \
  --save_steps=200 \
  --iterations=500